Refactor check_disk_smart_status for improved readability and maintainability
- Replace individual BIT_X variables with an associative array (ERROR_MESSAGES)
  for storing device error messages, improving scalability and organization.
- Simplify device list acquisition using smartctl --scan and direct parsing.
- Refactor bitmask error processing to dynamically retrieve and append messages
  from ERROR_MESSAGES, reducing redundancy.
- Improve loop structure for iterating over devices and SMART error checks.
- Replace string length check with more robust conditional ([[ -n ]]).
- Streamline error logging and exit behavior for clarity and maintainability.

diff --git a/src/usr/local/bin/check_disk_smart_status b/src/usr/local/bin/check_disk_smart_status
--- a/src/usr/local/bin/check_disk_smart_status
+++ b/src/usr/local/bin/check_disk_smart_status
@@ -1,66 +1,79 @@
 #!/bin/bash
-#################################################################################
-#                                                                               #
-# iscsi-ha - High Availability framework for iSCSI cluster used in conjunction  #
-# with XAPI based Xen Virtualization Environment (Xen Cloud Platform/XenServer) #
-# Copyright 2024 Salvatore Costantino                                           #
-# ha@ixi0.com                                                                   #
-#                                                                               #
-#                                                                               #
-#    iscsi-ha is free software: you can redistribute it and/or modify           #
-#    it under the terms of the GNU General Public License as published by       #
-#    the Free Software Foundation, either version 3 of the License, or          #
-#    (at your option) any later version.                                        #
-#                                                                               #
-#    iscsi-ha is distributed in the hope that it will be useful,                #
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of             #
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
-#    GNU General Public License for more details.                               #
-#                                                                               #
-#    You should have received a copy of the GNU General Public License          #
-#    along with iscsi-ha.  If not, see <http://www.gnu.org/licenses/>.          #
-#                                                                               #
-#################################################################################
+################################################################################
+#                                                                              #
+# iscsi-ha - HA Framework for iSCSI Cluster in Xen Virtualization              #
+#                                                                              #
+# Purpose:                                                                     #
+#    This script performs SMART checks on devices in an iSCSI cluster running  #
+#    within a Xen Virtualization Environment (Xen Cloud Platform / XenServer). #
+#    It scans each device for potential errors based on the SMART status and   #
+#    device self-test logs, logging errors if any are found.                   #
+#                                                                              #
+# Usage:                                                                       #
+#    ./check_disk_smart_status                                                 #
+#                                                                              #
+# Requirements:                                                                #
+#    - smartctl (from smartmontools) must be installed on the system.          #
+#    - The script requires root privileges to access SMART data from devices.  #
+#                                                                              #
+# License:                                                                     #
+#    This script is part of iscsi-ha, distributed under the GNU General Public #
+#    License v3 (GPL-3.0). You may redistribute and/or modify it under the     #
+#    terms of the GPL-3.0 License.                                             #
+#                                                                              #
+#    iscsi-ha is distributed in the hope that it will be useful, but WITHOUT   #
+#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or     #
+#    FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  #
+#    more details.                                                             #
+#                                                                              #
+# Author:                                                                      #
+#    Salvatore Costantino                                                      #
+#    ha@ixi0.com                                                               #
+#                                                                              #
+# Date:                                                                        #
+#    2024                                                                      #
+#                                                                              #
+################################################################################
 
+# List of device errors with corresponding messages
+declare -A ERROR_MESSAGES
+ERROR_MESSAGES=(
+  [0]="Command line did not parse."
+  [1]="Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode."
+  [2]="Some SMART or other ATA command to the disk failed, or there was a checksum error in a SMART data structure."
+  [3]="SMART status check returned 'DISK FAILING'."
+  [4]="We found prefail Attributes <= threshold."
+  [5]="SMART status check returned 'DISK OK' but we found that some attributes were <= threshold at some time."
+  [6]="The device error log contains records of errors."
+  [7]="The device self-test log contains records of errors. [ATA only] Failed self-tests outdated by a newer successful extended self-test are ignored."
+)
+
+# Initialize an empty error message list
 ERROR_MESSAGE_LIST=""
-DEVICE_LIST=$(smartctl --scan | awk {'print $1'})
 
-for disk in ${DEVICE_LIST}
-do
-	echo "Found device $disk"
+# Get the list of devices
+DEVICE_LIST=$(smartctl --scan | awk '{print $1}')
+
+# Iterate over each disk and perform SMART checks
+for disk in $DEVICE_LIST; do
+  echo "Found device: $disk"
+
+  # Run smartctl and check the return status
+  smartctl -q silent "$disk"
+  RETVAL=$?
+
+  # Check each bit in the return value
+  for ((i = 0; i < 8; i++)); do
+    THIS_BIT_VALUE=$((RETVAL & (2 ** i)))
+    if [[ $THIS_BIT_VALUE -ne 0 && $i -ne 0 && $i -ne 1 ]]; then
+      ERROR_MESSAGE_LIST+="${ERROR_MESSAGES[$i]}\n"
+    fi
+    echo "$disk: Bit $i = [ $THIS_BIT_VALUE ]"
+  done
 done
 
-############################
-## Bit mask error messages
-############################
-BIT_0='Command line did not parse.'
-BIT_1='Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode (see ´-n´ option above).'
-BIT_2='Some SMART or other ATA command to the disk failed, or there was a checksum error in a SMART data structure (see ´-b´ option above).'
-BIT_3='SMART status check returned "DISK FAILING".'
-BIT_4='We found prefail Attributes <= threshold.'
-BIT_5='SMART status check returned "DISK OK" but we found that some (usage or prefail) Attributes have been <= threshold at some time in the past.'
-BIT_6='The device error log contains records of errors.'
-BIT_7='The device self-test log contains records of errors.  [ATA only] Failed self-tests outdated by a newer successful extended self-test are ignored.'
-
-for device in ${DEVICE_LIST[@]}
-do
-	smartctl -q silent $device
-	RETVAL=$?
-	for ((i=0; i<8; i++))
-	do
-		THIS_BIT_VALUE=$((RETVAL & 2**i && 1))
-		if [ $THIS_BIT_VALUE -ne 0  -a $i -ne 0 -a $i -ne 1 ]
-		then
-			ERROR_MESSAGE="BIT_$i"
-			ERROR_MESSAGE_LIST+="${!ERROR_MESSAGE}\n"
-		fi
-		echo "$device: Bit $i = [ $THIS_BIT_VALUE ]"
-	done
-done
-
-if [ ${#ERROR_MESSAGE_LIST} -gt 0 ]
-then
-	## We have errors - log, print, email?
-	echo -e $ERROR_MESSAGE_LIST
-	exit 1
+# If there are any errors, log and handle them
+if [[ -n "$ERROR_MESSAGE_LIST" ]]; then
+  echo -e "$ERROR_MESSAGE_LIST"
+  exit 1
 fi
