Refactor recover_forgotten_host script:
- Added user confirmation prompt requiring 'YES' to continue
- Improved warning messages with 80-character line breaks
- Enhanced script readability and ensured consistent formatting

diff --git a/src/usr/local/bin/recover_forgotten_host b/src/usr/local/bin/recover_forgotten_host
--- a/src/usr/local/bin/recover_forgotten_host
+++ b/src/usr/local/bin/recover_forgotten_host
@@ -1,61 +1,106 @@
+#!/bin/bash
+#################################################################################
+#                                                                               #
+# recover_forgotten_host - Script to prepare a host for reintroduction to a     #
+# pool. This script is for hosts with no local storage used to serve VMs. ALL   #
+# pool state information will be erased, and Ethernet and management interfaces  #
+# will be reset with new values entered here. The host will reboot when finished.#
+#                                                                               #
+# Usage:                                                                       #
+#   This script prompts the user to confirm if they want to proceed with the    #
+#   recovery process. Type 'YES' to continue or press <Ctrl+C> to abort.        #
+#                                                                               #
+# Author: Salvatore Costantino (2024)                                           #
+# Email: ha@ixi0.com                                                            #
+#                                                                               #
+# License: GNU General Public License v3.0 or later                             #
+#                                                                               #
+#################################################################################
+
 clear
-echo "###################################################################################################################"
-echo "###################################################################################################################"
-echo "## DO NOT CONTINUE unless you know what you are doing                                                            ##"
-echo "## This script tries to prepare a host that has been forgotten for reintroduction to a pool                      ##"
-echo "## It is intended for hosts with no local storage used to serve VMs - ALL pool state information will be erased  ##"
-echo "## Ethernet and management interfaces will be reset with new values entered here. Host will reboot when finished ##"
-echo "## Control + C to exit or <Enter> to continue                                                                    ##"
-echo "###################################################################################################################"
-echo "###################################################################################################################"
-read n1
 
+# Set the color to red for warning messages
+RED="\033[31m"
+# Reset the color back to default
+RESET="\033[0m"
 
-HOST_MODE=`xe host-is-in-emergency-mode`
-if [ $HOST_MODE = "true" ]
-then
-	echo "Host is in emergency mode - attempt resetting host? Enter [ yes or no ]"
-	read CONTINUE
+# Display the warning message in red
+echo -e "${RED}"
+cat <<EOF
+################################################################################
+################################################################################
+## DO NOT CONTINUE unless you know what you are doing.                        ##
+## This script tries to prepare a host that has been forgotten for            ##
+## reintroduction to a pool. It is intended for hosts with no local storage   ##
+## used to serve VMs. ALL pool state information will be erased. Ethernet and ##
+## management interfaces will be reset with new values entered here. Host     ##
+## will reboot when finished.                                                 ##
+##                                                                            ##
+## Type 'YES' to continue or press <Ctrl+C> to exit                           ##
+################################################################################
+################################################################################
+
+EOF
+echo -e "${RESET}"
+
+# Wait for user input, only proceed if 'YES' is typed
+read -r user_input
+if [[ "$user_input" != "YES" ]]; then
+  echo "Aborting... Invalid input"
+  exit 1
+fi
+
+# Check if the host is in emergency mode
+HOST_MODE=$(xe host-is-in-emergency-mode)
+if [ "$HOST_MODE" = "true" ]; then
+  echo "Host is in emergency mode - attempt resetting host? Enter [ yes or no ]"
+  read -r CONTINUE
 else
-	echo "Host is not in emergency mode - Host may be recovered by alternate means. continue? Enter [ yes or no ]"
-	read CONTINUE
+  echo "Host is not in emergency mode - Host may be recovered by alternate means. Continue? Enter [ yes or no ]"
+  read -r CONTINUE
 fi
 
-if [ $CONTINUE = "no" ]
-then
-	exit 1
-elif [ $CONTINUE = "yes" ]
-then
-	echo "Continuing"
+# Validate user input
+if [ "$CONTINUE" = "no" ]; then
+  exit 1
+elif [ "$CONTINUE" = "yes" ]; then
+  echo "Continuing"
 else
-	echo "Invalid Input - exiting"
-	exit 1
+  echo "Invalid Input - exiting"
+  exit 1
 fi
 
-NOW=`date +"%g%m%d_%H%M%S"`
-echo "Moving  XAPI state files to /var/xapi/state.db.old$NOW /var/xapi/local.db.old$NOW"
-mv /var/xapi/state.db /var/xapi/state.db.old$NOW && mv /var/xapi/local.db /var/xapi/local.db.old$NOW
-if [ $? = 0 ]; then
-        echo "Successfully moved XAPI state files"
+# Prepare for the recovery process
+NOW=$(date +"%g%m%d_%H%M%S")
+echo "Moving XAPI state files to /var/xapi/state.db.old-$NOW /var/xapi/local.db.old-$NOW"
+if mv /var/xapi/state.db "/var/xapi/state.db.old-$NOW" && mv /var/xapi/local.db "/var/xapi/local.db.old-$NOW"; then
+  echo "Successfully moved XAPI state files"
+else
+  echo "Failed to move XAPI state files"
+  exit 1
 fi
 
+# Switch to master mode
 echo "Switching to master"
-
-echo master > /etc/xensource/pool.conf
-if [ $? = 0 ]; then
-	echo "Successfully set host mode to master"
+if echo master >/etc/xensource/pool.conf; then
+  echo "Successfully set host mode to master"
+else
+  echo "Failed to set host mode to master"
+  exit 1
 fi
 
+# Gather new networking details
 echo "Enter new IP information for host. Host will reset when done"
 echo "Enter new IP address"
-read IP
+read -r IP
 echo "Enter subnet mask"
-read NETMASK
+read -r NETMASK
 echo "Enter default gateway"
-read GATEWAY
+read -r GATEWAY
 echo "Enter DNS server IP"
-read DNS
+read -r DNS
 echo "Enter mode - static or dhcp"
-read MODE
+read -r MODE
 
-xe-reset-networking --ip=$IP --netmask=$NETMASK --gateway=$GATEWAY --dns=$DNS --mode=$MODE
+# Reset the networking configuration
+xe-reset-networking --ip="$IP" --netmask="$NETMASK" --gateway="$GATEWAY" --dns="$DNS" --mode="$MODE"
